p4-django-project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('poll/', include('poll.urls', namespace='poll'), name='poll_urls'),
    path('admin/', admin.site.urls),
    path("", include("website.urls"), name="website_urls"),
    path('summernote/', include('django_summernote.urls')),
    path("accounts/", include("allauth.urls")),
]

poll/urls.py
from django.urls import path

from . import views


# Credits - please note this code is sourced from the
# Official Django documentation on poll tutorials and
# is fully acknowledged & accredited in readme
app_name = 'poll'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

poll/models.py
import datetime

from django.db import models
from django.utils import timezone


# Credits - this code is sourced from the official Django documentation
# tutorials and is fully accredited in readme credits
# Create your models here.
class Question(models.Model):
    """
    The Question Model with attributes for content and dates
    and methods to display the question text and pulication date
    """
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    """
    The Choice Model with attributes for text and votes, a foreign key
    to the question model and methods to display the choice text
    """
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

poll/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Question, Choice

# Create your views here.
# Credits - please note this code is sourced from the
# Official Django documentation on poll tutorials and
# is fully acknowledged & accredited in readme


class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'poll/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()).order_by('pub_date')[:5]


class DetailView(LoginRequiredMixin, generic.DetailView):
    model = Question
    template_name = 'poll/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(LoginRequiredMixin, generic.DetailView):
    model = Question
    template_name = 'poll/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'poll/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(
            reverse('poll:results', args=(question.id,)))

poll/templates/poll/detail.html
{% extends "base.html" %}

{% block content %}
<!-- Setup bootstrap responsive grid -->
<div class="container-fluid text-light text-center">    
    <div class="row align-items-center home-page-container">
        <div class="col">
            <!-- Summary field for question title - using bootstrap responsivity features-->
            <div class="row justify-content-center">
                <div class="col-sm-10 col-md-10 col-xxl-8 green border d-flex justify-content-center align-items-center my-4 mx-1">
                    <i class="rocket fas fa-clipboard text-dark pe-3"></i> 
                        <h2 class="pb-3 pt-3 pe-2 text-center text-dark">Question {{ question.id }}</h2><h2 class="pb-3 pt-3 text-light font-weight-bold">{{ question.question_text }}</h2>
                    <i class="rocket fas fa-clipboard text-dark ps-3"></i> 
                </div>
            </div>
            <!-- Detail section for answer choices using bootstrap responsivity features -->
            <div class="row justify-content-center">
                <div class="col-sm-10 col-md-10 col-xxl-3 green border mb-4 mx-1">                    
                    <form action="{% url 'poll:vote' question.id %}" method="post">
                        {% csrf_token %}
                        <fieldset>                            
                            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                            {% for choice in question.choice_set.all %}
                                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                                <label class="text-light" for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
                            {% endfor %}
                        </fieldset>                        
                        <!-- Button for user to register their vote - use site color palette & theme -->
                        <input class ="btn-dark" type="submit" value="Vote">
                    </form>
                </div>
            </div>        
        </div>
    </div>
</div>


{%endblock%}

poll/templates/poll/index.html
{% extends "base.html" %}

{% block content %}
<!-- Setup bootstrap responsive grid -->
<div class="container-fluid text-light text-center">    
    <div class="row align-items-center home-page-container">
        <div class="col">
            <!-- Summary field for Polls Summary page - using bootstrap responsivity features-->
            <div class="row justify-content-center">
                <div class="col-sm-10 col-md-10 col-xxl-8 green border d-flex justify-content-center align-items-center my-4 mx-1">
                    <i class="rocket fas fa-rocket text-dark pe-4"></i> 
                        <h1 class="pb-3 pt-3 pe-2 text-center text-dark">Django Blog </h1><h1 class="pb-3 pt-3 text-light font-weight-bold">|Opinion Polls|</h1>
                    <i class="rocket fas fa-rocket text-dark ps-4"></i> 
                </div>
            </div>
            <!-- Detail section for introductory context using bootstrap responsivity features -->
            <div class="row justify-content-center">
                <div class="col-sm-10 col-md-10 col-xxl-8 green border mb-4 mx-1">
                    <h2 class="pt-3 pb-2">Polls Overview<i class="fas fa-clipboard text-dark ps-3"></i></h2>
                    <p>Welcome to Django Blog's Opinion Polls, this page will enable you to participate in our opinion poll questions covering important aspects of the site content</p>
                    <p>Please take a second to vote by clicking on any of the opinion polls listed below: </p>
                    <a class = "btn btn-dark my-2" href="{% url 'home' %}" role="button">Return Home</a> 
                </div>
            </div>
            <!-- Detail section for question text using bootstrap responsivity features -->
            <div class="row justify-content-center">
                {% if latest_question_list %}                                    
                    {% for question in latest_question_list %}
                        <div class="col-sm-5 col-md-5 col-xxl-4 green border mb-2 mx-1">
                            <h3 class="pt-3 pb-2">Polls: Question {{ question.id }}<i class="fas fa-book text-dark ps-3"></i></h3> 
                                <p>{{ question.question_text }}</p>        
                            <!-- Button for user to go to desired poll - use site color palette & theme -->                        
                            <a class = "btn btn-dark mb-2" href="{% url 'poll:detail' question.id %}" role="button">Go To Poll {{ question.id }}</a>
                        </div>                        
                    {% endfor %}                                    
                {% else %}
                    <p>No polls are available.</p>
                {% endif %}
            </div>            
        
        </div>
    </div>
</div>

{% endblock %}

poll/templates/poll/results.html
{% extends "base.html" %}

{% block content %}

<!-- Setup bootstrap responsive grid -->
<div class="container-fluid text-light text-center">    
    <div class="row align-items-center home-page-container">
        <div class="col">
            <!-- Summary field Question Text - using bootstrap responsivity features-->
            <div class="row justify-content-center">
                <div class="col-sm-10 col-md-10 col-xxl-8 green border d-flex justify-content-center align-items-center my-4 mx-1">
                    <i class="rocket fas fa-clipboard text-dark pe-3"></i> 
                        <h2 class="py-3 pe-2 text-center text-dark font-weight-bold">Results</h2><h2 class="pb-3 pt-3 text-light">{{ question.question_text }}</h2>
                    <i class="rocket fas fa-clipboard text-dark ps-3"></i> 
                </div>
            </div>
            <!-- Detail section for votes per answer choice using bootstrap responsivity features -->
            <div class="row justify-content-center">
                <div class="col-sm-10 col-md-10 col-xxl-3 green border mb-4 mx-1 pt-3">
                    {% for choice in question.choice_set.all %}
                        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
                    {% endfor %}
                <!-- Buttons for user to go back to polls or go to home page - use site color palette & theme -->
                <a class = "btn btn-dark my-3" href="{% url 'poll:index' %}">Return To Polls</a>
                <a class = "btn btn-dark my-3" href="{% url 'home' %}">Return Home</a>
                </div>
                
            </div>        
        </div>
    </div>
</div>

{% endblock %}